# Generated by Django 4.2.20 on 2025-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(help_text='Example: +91-9876543210, 5551234567', max_length=15, unique=True),
        ),
    ]
