# Generated by Django 4.2.20 on 2025-10-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Unique email used for login', max_length=254, unique=True),
        ),
    ]
