# Generated by Django 5.2.7 on 2025-11-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='title',
            field=models.CharField(blank=True, help_text='Enter a descriptive title for the auction', max_length=255),
        ),
    ]
