# Generated by Django 4.2.20 on 2025-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_dealerprofile_created_at_dealerprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofile',
            name='address',
            field=models.CharField(help_text='Example: 123 Main St, Downtown, Suite 400', max_length=255),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='city',
            field=models.CharField(help_text='Example: Hyderabad, Mumbai, New York', max_length=100),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='company_name',
            field=models.CharField(help_text='Example: Sunrise Auto Group, Elite Motors, City Cars', max_length=255),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='country',
            field=models.CharField(help_text='Example: India, USA, Canada', max_length=100),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Example: info@sunriseauto.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload company logo (PNG/JPG)', null=True, upload_to='dealer_logos/'),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='phone',
            field=models.CharField(help_text='Example: +91-9876543210, (555) 123-4567', max_length=20),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='state',
            field=models.CharField(help_text='Example: Telangana, California, Maharashtra', max_length=100),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Example: https://www.sunriseauto.com', max_length=255),
        ),
    ]
