# Generated by Django 4.2.20 on 2025-10-28 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(help_text='Example: 1HGCM82633A004352 (17-character Vehicle Identification Number)', max_length=17, unique=True)),
                ('make', models.CharField(help_text='Example: Toyota, Ford, BMW, Tesla', max_length=100)),
                ('model', models.CharField(help_text='Example: Camry, F-150, 3 Series, Model S', max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Example: 2022')),
                ('color', models.CharField(help_text='Example: Red, Blue, Black, White', max_length=50)),
                ('mileage', models.PositiveIntegerField(help_text='Example: 25000 (in kilometers or miles)')),
                ('features', models.TextField(blank=True, help_text='Example: Sunroof, Leather seats, Bluetooth, Backup camera')),
                ('description', models.TextField(blank=True, help_text='Example: Well-maintained, single owner, accident-free.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Example: 18500.00', max_digits=12, null=True)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, help_text='Example: 15000.00 (minimum bid price)', max_digits=12, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT'), ('semi-automatic', 'Semi-Automatic')], max_length=20)),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG'), ('lpg', 'LPG'), ('other', 'Other')], max_length=20)),
                ('body_style', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('van', 'Van'), ('pickup', 'Pickup'), ('other', 'Other')], max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('pending', 'Pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
        ),
    ]
