# Generated by Django 4.2.20 on 2025-07-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_created_at_vehicle_dealer_vehicle_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
