# Generated by Django 4.2.20 on 2025-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_starting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(help_text='Example: Red, Blue, Black, White', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, help_text='Example: Well-maintained, single owner, accident-free.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='features',
            field=models.TextField(blank=True, help_text='Example: Sunroof, Leather seats, Bluetooth, Backup camera'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(help_text='Example: Toyota, Ford, BMW, Tesla', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(help_text='Example: 25000 (in kilometers or miles)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(help_text='Example: Camry, F-150, 3 Series, Model S', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Example: 18500.00', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Example: 15000.00 (minimum bid price)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(help_text='Example: 1HGCM82633A004352 (17-character Vehicle Identification Number)', max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(help_text='Example: 2022'),
        ),
    ]
